import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

import StyledComponentsRegistry from "./registry";

const mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mono.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
